# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Alpha Build to Google Play"
  lane :beta do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'alpha', skip_upload_apk: true)

    gradle(task: "assemble")
    amazon_app_submission(
        client_id: ENV['AMAZON_DEV_CLIENTID'],
        client_secret: ENV['AMAZON_DEV_SECRET'],
        app_id: "amzn1.devportal.mobileapp.fae1c668e01c49cd96c5719c4a8db1cb",
        apk_path: "./app/build/outputs/apk/release/app-release.apk",
        upload_apk: true,
        submit_for_review: true,
        changelogs_path: './fastlane/metadata/android/fr-FR/changelogs',
        upload_changelogs: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
